import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {validateContent} from '../dist/schema.js';
import {doiValue,paperFromCrossref,paperFromText,patentFromText,upsertImported,ensureJournal,journalMetric,parseMetricCSV} from '../dist/publication-data.js';
import {refreshJournal,reportMetric} from './refresh-jif.mjs';
const metadata={DOI:'10.1234/eeml.test',title:['Interfacial stability in lithium metal batteries'],author:[{given:'Min',family:'Kim'},{given:'Alex',family:'Lee'}],'container-title':['Example Journal'],ISSN:['1234-567X'],published:{'date-parts':[[2025,5,1]]},resource:{primary:{URL:'https://example.org/article'}},type:'journal-article'};
const text='Interfacial stability in lithium metal batteries\nMin Kim, Alex Lee\nhttps://doi.org/10.1234/eeml.test\nKeywords: Lithium metal; Electrolytes; Interfacial chemistry\nAbstract\nWe study interfacial chemistry in batteries.';
const paper=paperFromCrossref(metadata,text);assert.equal(paper.year,2025);assert.equal(paper.authors,'Min Kim, Alex Lee');assert.equal(paper.keywords.split(';').length,3);assert.equal(paper.articleUrl,'https://example.org/article');assert.equal(doiValue('https://doi.org/10.1234/(abc).'),'10.1234/(abc)');
assert.equal(doiValue('http://crossmark.crossref.org/dialog/?doi=10.1007/s40820-026-02167-y&domain=pdf'),'10.1007/s40820-026-02167-y');
assert.equal(doiValue('https://crossmark.crossref.org/dialog/?doi=10.1007%2Fs40820-026-02167-y&domain=pdf'),'10.1007/s40820-026-02167-y');
assert.equal(doiValue('https://doi.org/10.1007/s40820-026-02167-y?source=pdf#page=1'),'10.1007/s40820-026-02167-y');
const templatedTitle='Block Copolymer-Templated Interfaces for Stable Battery Anodes';
assert.equal(paperFromText('Published online: 6 May 2026\n'+templatedTitle+'\nMin Kim, Alex Lee\nAbstract\nBattery study.',{Title:templatedTitle}).title,templatedTitle);
assert.equal(paperFromText('Published online: 6 May 2026\nAbstract\nBattery study.').title,'');
assert.equal(paperFromText('Copyright 2025\n'+text,{CreationDate:'D:20260913000000'}).year,'');
const app=patentFromText('대한민국 특허청\n출원번호: 10-2025-1234567\n출원일: 2025.03.04\n발명의 명칭: 전지용 계면 안정화 방법\n발명자: 김연구, 박전지\n주소: 예시 주소');assert.equal(app.status,'출원');assert.equal(app.date,'2025-03-04');assert.equal(app.title,'전지용 계면 안정화 방법');assert.equal(app.inventors,'김연구, 박전지');
const reg=patentFromText('대한민국 특허증\n등록번호: 10-2345678\n등록일: 2026년 04월 05일\n출원번호: 10-2025-1234567\n출원일: 2025.03.04\n발명의 명칭: 전지용 계면 안정화 방법\n발명자: 김연구, 박전지');assert.equal(reg.status,'등록');assert.equal(reg.date,'2026-04-05');const patents=[{id:'retained',...app}];assert.equal(upsertImported(patents,reg,'patents').action,'updated');assert.equal(patents.length,1);assert.equal(patents[0].id,'retained');assert.equal(patents[0].status,'등록');assert.equal(patents[0].number,'10-2345678');assert.equal(upsertImported(patents,reg,'patents').action,'duplicate');
const papers=[];assert.equal(upsertImported(papers,{id:'first',...paper},'publications').action,'added');assert.equal(upsertImported(papers,{id:'second',...paper},'publications').action,'duplicate');assert.equal(papers.length,1);
const journals=[];ensureJournal(paper,journals);ensureJournal({...paper,venue:'Example Journal abbreviated'},journals);assert.equal(journals.length,1);assert.equal(journalMetric(paper,journals).label,'IF —');
const csv=parseMetricCSV('name,issn,impactFactor,metricYear,metricSource,metricUpdated\n"Example, Journal",1234-567X,<0.1,2025,https://example.org/metrics,2026-09-01\n');assert.equal(csv[0].name,'Example, Journal');assert.equal(csv[0].impactFactor,'<0.1');
const calls=[];const response=await refreshJournal(journals[0],async path=>{calls.push(path);if(path.startsWith('/journals?q='))return {hits:[{id:'EXAMPLE'}]};if(path==='/journals/EXAMPLE')return {issn:'1234-567X',journalCitationReports:[{year:2024,url:'https://example.org/2024'},{year:2025,url:'https://example.org/2025'}]};if(path==='/journals/EXAMPLE/reports/year/2025')return {year:2025,metrics:{impactMetrics:{jif:'<0.1'}}};throw new Error(path);},'2026-09-12');assert.equal(response.patch.impactFactor,'<0.1');assert.equal(response.patch.metricYear,2025);Object.assign(journals[0],response.patch);assert.equal(journalMetric({...paper,impactFactor:response.patch.impactFactor,metricYear:response.patch.metricYear}).label,'IF <0.1 · 2025');assert.equal(reportMetric({year:2025,suppressed:true,metrics:{impactMetrics:{jif:'99'}}},'https://example.org','2026-09-12').impactFactor,'');assert.equal(reportMetric({year:2025,metrics:{impactMetrics:{jif:'N/A'}}},'https://example.org','2026-09-12').metricStatus,'미제공');
const base=validateContent(JSON.parse(await readFile(new URL('../dist/data/content.json',import.meta.url),'utf8')));assert.deepEqual(validateContent(JSON.parse(JSON.stringify(base))),base);const bad=structuredClone(base);bad.journals[0].metricStatus='확인됨';assert.throws(()=>validateContent(bad),/Verified IF/);
console.log('PASS: bibliographic fields, 3 keywords, DOI duplicates, patent application→registration, journal identity, CSV, latest JIF year and unavailable status.');
// Real PDF decoding using a minimal in-memory text PDF; no user document is transmitted.
if(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES){const require=createRequire(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/package.json');const canvas=require('@napi-rs/canvas');globalThis.DOMMatrix=canvas.DOMMatrix;globalThis.Path2D=canvas.Path2D;globalThis.ImageData=canvas.ImageData;}
function textPDF(lines){const stream='BT /F1 12 Tf 50 760 Td 17 TL '+lines.map((line,i)=>(i?'T* ':'')+'('+line.replace(/[\\()]/g,'\\$&')+') Tj').join('\n')+' ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Length '+Buffer.byteLength(stream)+' >>\nstream\n'+stream+'\nendstream'];let pdf='%PDF-1.4\n',offsets=[0];for(const [i,obj] of objects.entries()){offsets.push(Buffer.byteLength(pdf));pdf+=(i+1)+' 0 obj\n'+obj+'\nendobj\n';}const start=Buffer.byteLength(pdf);pdf+='xref\n0 '+offsets.length+'\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size '+offsets.length+' /Root 1 0 R >>\nstartxref\n'+start+'\n%%EOF';return new File([pdf],'paper.pdf',{type:'application/pdf'});}
const originalFetch=globalThis.fetch;globalThis.fetch=async (url,options)=>String(url).startsWith('https://api.crossref.org/')?new Response(JSON.stringify({message:metadata}),{status:200,headers:{'Content-Type':'application/json'}}):originalFetch(url,options);
try{const {importDocument}=await import('../dist/document-import.js');const result=await importDocument(textPDF(text.split('\n')),'publications',()=>{});assert.equal(result.title,metadata.title[0]);assert.equal(result.authors,'Min Kim, Alex Lee');assert.equal(result.year,2025);assert.equal(result.sourceHash.length,64);assert.equal(result.keywords.split(';').length,3);console.log('PASS: real PDF bytes → extracted text → DOI lookup adapter → ready-to-edit paper record.');}catch(error){console.error(error.name+': '+error.message);process.exitCode=1;}finally{globalThis.fetch=originalFetch;}

// A missing first DOI must not stop lookup of the paper's valid DOI.
const fallbackCalls=[],laterMetadata={...metadata,DOI:'10.1234/later-valid'};
globalThis.fetch=async url=>{fallbackCalls.push(String(url));return String(url).includes(encodeURIComponent(laterMetadata.DOI))?new Response(JSON.stringify({message:laterMetadata}),{status:200}):new Response('{}',{status:404});};
try{const {importDocument}=await import('../dist/document-import.js');const result=await importDocument(textPDF(['https://doi.org/10.1234/missing',...text.replace(metadata.DOI,laterMetadata.DOI).split('\n')]),'publications');assert.equal(result.doi,'https://doi.org/'+laterMetadata.DOI);assert.equal(result.authors,'Min Kim, Alex Lee');assert.equal(fallbackCalls.length,2);console.log('PASS: invalid DOI candidate does not prevent valid DOI import.');}finally{globalThis.fetch=originalFetch;}

// If online lookup is unavailable, preserve local fields instead of failing.
globalThis.fetch=async()=>{throw new TypeError('Offline');};
try{const {importDocument}=await import('../dist/document-import.js');const result=await importDocument(textPDF([metadata.title[0],'Min Kim, Alex Lee','Published online: 6 May 2026','https://doi.org/10.1234/offline-test','Abstract','A study of battery interfaces.']),'publications');assert.equal(result.title,metadata.title[0]);assert.equal(result.authors,'Min Kim, Alex Lee');assert.equal(result.year,2026);assert.equal(result.doi,'https://doi.org/10.1234/offline-test');assert.match(result.importNote,/Online metadata unavailable/);console.log('PASS: local bibliographic fields retained when online lookup fails.');}finally{globalThis.fetch=originalFetch;}
